name: Node.js Package

on:
  release:
    types: [created]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish-npm:
    #needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: latest
          check-latest: true

      - run: npm i
      - run: cd test && npm i

      - run: npm publish
